In [5]:
#IMPORTS
import sys
import os
import pandas as pd
#Fix Notebook Path
sys.path.append(os.path.abspath(".."))

from src.preprocessing_data.pre_processing import PreProcessor
from src.models.train_model import BasicLogisticRegressionTraining

In [6]:
#CONSTANTS
FILEPATH = "../src/data/raw/all_reviews.csv"
TRAIN_PATH = "../src/data/processed/train.csv"
TEST_PATH = "../src/data/processed/test.csv"

In [3]:
pd.set_option("display.max_columns", None)
FILEPATH = "../src/data/raw/all_reviews.csv"

nrows = 10000  #Number of rows limited to 100,000 to reduce run time
x = PreProcessor(FILEPATH)
df = x.load_data(nrows)
df.head()

,recommendationid,appid,game,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,hidden_in_steam_china,steam_china_location
0,148919893,10,Counter-Strike,76561199036724879,0,3,197,197,197,1698336369,russian,старость,1698336397,1698336397,1,0,0,0.0,0,1,0,0,1,NaN
1,148919350,10,Counter-Strike,76561198826729322,0,21,441,37,441,1698335809,russian,Лучше кс 2,1698335821,1698335821,1,0,0,0.0,0,1,0,0,1,NaN
2,148913051,10,Counter-Strike,76561199101237625,7,1,1440,1440,1313,1698338635,turkish,çoh iyi ama pahalı,1698329862,1698329862,1,0,0,0.0,0,1,0,0,1,NaN
3,148912714,10,Counter-Strike,76561198347582422,11,4,1636,83,1612,1698341834,russian,топ,1698329555,1698329555,1,0,0,0.0,0,1,0,0,1,NaN
4,148912575,10,Counter-Strike,76561198363716821,0,2,197,41,197,1698329401,english,GOAT Game !!,1698329419,1698329419,1,0,0,0.0,0,1,0,0,1,NaN

In [13]:
print((df["review"].str.strip() == "").sum())
print("________________________")
nan_count = df.isna().sum()
print(nan_count)

6
________________________
recommendationid                      0
appid                                 0
game                                  0
author_steamid                        0
author_num_games_owned                0
author_num_reviews                    0
author_playtime_forever               0
author_playtime_last_two_weeks        0
author_playtime_at_review             0
author_last_played                    0
language                              0
review                                0
timestamp_created                     0
timestamp_updated                     0
voted_up                              0
votes_up                              0
votes_funny                           0
weighted_vote_score                   0
comment_count                         0
steam_purchase                        0
received_for_free                     0
written_during_early_access           0
hidden_in_steam_china                 0
steam_china_location              10000
dtype: int64

In [14]:
df = x.preprocess(nrows)
df.head()

,game,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access
0,Counter-Strike,76561199036724879,0,3,197,197,197,2023-10-26 16:06:09,russian,старость,2023-10-26 16:06:37,2023-10-26 16:06:37,1,0,0,0.0,0,1,0,0
1,Counter-Strike,76561198826729322,0,21,441,37,441,2023-10-26 15:56:49,russian,Лучше кс 2,2023-10-26 15:57:01,2023-10-26 15:57:01,1,0,0,0.0,0,1,0,0
2,Counter-Strike,76561199101237625,7,1,1440,1440,1313,2023-10-26 16:43:55,turkish,çoh iyi ama pahalı,2023-10-26 14:17:42,2023-10-26 14:17:42,1,0,0,0.0,0,1,0,0
3,Counter-Strike,76561198347582422,11,4,1636,83,1612,2023-10-26 17:37:14,russian,топ,2023-10-26 14:12:35,2023-10-26 14:12:35,1,0,0,0.0,0,1,0,0
4,Counter-Strike,76561198363716821,0,2,197,41,197,2023-10-26 14:10:01,english,GOAT Game !!,2023-10-26 14:10:19,2023-10-26 14:10:19,1,0,0,0.0,0,1,0,0

In [15]:
print((df["review"].str.strip() == "").sum())
print("________________________")
nan_count = df.isna().sum()
print(nan_count)

0
________________________
game                              0
author_steamid                    0
author_num_games_owned            0
author_num_reviews                0
author_playtime_forever           0
author_playtime_last_two_weeks    0
author_playtime_at_review         0
author_last_played                0
language                          0
review                            0
timestamp_created                 0
timestamp_updated                 0
voted_up                          0
votes_up                          0
votes_funny                       0
weighted_vote_score               0
comment_count                     0
steam_purchase                    0
received_for_free                 0
written_during_early_access       0
dtype: int64

In [7]:
lr = BasicLogisticRegressionTesting(TRAIN_PATH,TEST_PATH)
results = lr.run_lr_pipeline()
print(results)

NameError: name 'BasicLogisticRegression' is not defined