In [9]:
#IMPORTS
import sys
import os
import pandas as pd
#Fix Notebook Path
sys.path.append(os.path.abspath(".."))

from src.preprocessing_data.pre_processing import PreProcessor
from src.models.train_model import BasicLogisticRegressionTraining

In [10]:
#CONSTANTS
FILEPATH = "../src/data/raw/all_reviews.csv"
TRAIN_PATH = "../src/data/processed/train.csv"
TEST_PATH = "../src/data/processed/test.csv"

In [11]:
pd.set_option("display.max_columns", None)
FILEPATH = "../src/data/raw/all_reviews.csv"

nrows = 10000  #Number of rows limited to 100,000 to reduce run time
x = PreProcessor(FILEPATH)
df = x.load_data(nrows)
df.head()

,recommendationid,appid,game,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,hidden_in_steam_china,steam_china_location
0,148919893,10,Counter-Strike,76561199036724879,0,3,197,197,197,1698336369,russian,старость,1698336397,1698336397,1,0,0,0.0,0,1,0,0,1,NaN
1,148919350,10,Counter-Strike,76561198826729322,0,21,441,37,441,1698335809,russian,Лучше кс 2,1698335821,1698335821,1,0,0,0.0,0,1,0,0,1,NaN
2,148913051,10,Counter-Strike,76561199101237625,7,1,1440,1440,1313,1698338635,turkish,çoh iyi ama pahalı,1698329862,1698329862,1,0,0,0.0,0,1,0,0,1,NaN
3,148912714,10,Counter-Strike,76561198347582422,11,4,1636,83,1612,1698341834,russian,топ,1698329555,1698329555,1,0,0,0.0,0,1,0,0,1,NaN
4,148912575,10,Counter-Strike,76561198363716821,0,2,197,41,197,1698329401,english,GOAT Game !!,1698329419,1698329419,1,0,0,0.0,0,1,0,0,1,NaN

In [12]:
print((df["review"].str.strip() == "").sum())
print("________________________")
nan_count = df.isna().sum()
print(nan_count)

6
________________________
recommendationid                      0
appid                                 0
game                                  0
author_steamid                        0
author_num_games_owned                0
author_num_reviews                    0
author_playtime_forever               0
author_playtime_last_two_weeks        0
author_playtime_at_review             0
author_last_played                    0
language                              0
review                                0
timestamp_created                     0
timestamp_updated                     0
voted_up                              0
votes_up                              0
votes_funny                           0
weighted_vote_score                   0
comment_count                         0
steam_purchase                        0
received_for_free                     0
written_during_early_access           0
hidden_in_steam_china                 0
steam_china_location              10000
dtype: int64

In [13]:
df = x.preprocess(nrows)
df.head()

-------------------------
Current Dataframe has 2,011 rows and 20 columns.
No missing values found.

1,925 reviews are positive (95.7%) and 86 are negative (4.3%).

On average, authors have played for 21,716 minutes (median: 1,215, longest: 789,222).
At the time of writing, authors had played for 19,089 minutes on average (median: 695, longest: 786,081).

Reviews are 14.0 words long on average (median: 3, longest: 572 words).

Authors have written 20.5 reviews on average (median: 5, most prolific: 6,317).
Authors own 58.1 games on average (median: 11, most: 6,085).

Of the reviews in this dataframe:
  1,529 (76.0%) were purchased on Steam.
  117 (5.8%) were received for free.
  0 (0.0%) were written during early access.

The current dataframe covers 1 unique game(s).
-------------------------

,game,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,language,review,timestamp_created,timestamp_updated,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access
4,Counter-Strike,76561198363716821,0,2,197,41,197,2023-10-26 14:10:01,english,GOAT Game !!,2023-10-26 14:10:19,2023-10-26 14:10:19,1,0,0,0.00000,0,1,0,0
10,Counter-Strike,76561198134752176,69,1,12107,0,12107,2022-12-08 08:24:51,english,First crush. Always in my heart.,2023-10-26 07:41:36,2023-10-26 07:41:36,1,0,0,0.00000,0,0,0,0
11,Counter-Strike,76561197985437504,0,5,42519,3,42515,2023-10-26 07:36:51,english,"best version of cs ever, history.",2023-10-26 07:32:49,2023-10-26 07:32:49,1,0,0,0.00000,0,0,0,0
25,Counter-Strike,76561199015747395,71,34,30,0,30,2021-12-16 04:05:18,english,"a game everyone needs, but not to play.",2023-10-25 18:11:55,2023-10-25 18:11:55,1,0,0,0.00000,0,1,0,0
28,Counter-Strike,76561199479067349,5,6,209,200,209,2023-10-19 23:22:41,english,old but gold,2023-10-25 17:03:14,2023-10-25 17:03:14,1,1,0,0.52381,0,1,0,0

In [14]:
print((df["review"].str.strip() == "").sum())
print("________________________")
nan_count = df.isna().sum()
print(nan_count)

0
________________________
game                              0
author_steamid                    0
author_num_games_owned            0
author_num_reviews                0
author_playtime_forever           0
author_playtime_last_two_weeks    0
author_playtime_at_review         0
author_last_played                0
language                          0
review                            0
timestamp_created                 0
timestamp_updated                 0
voted_up                          0
votes_up                          0
votes_funny                       0
weighted_vote_score               0
comment_count                     0
steam_purchase                    0
received_for_free                 0
written_during_early_access       0
dtype: int64

In [15]:
lr = BasicLogisticRegressionTraining(TRAIN_PATH,TEST_PATH)
lr = BasicLogisticRegressionTraining(TRAIN_PATH,TEST_PATH)
results = lr.run_lr_pipeline()
print(results)

{'accuracy': 0.6896249211210811, 'precision': 0.9271170735956792, 'recall': 0.6953309218771345, 'f1_score': 0.794667282119511, 'confusion_matrix': array([[ 17353,   9203],
       [ 51295, 117068]])}